/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AplikasiPenampilGambar;

/**
 *
 * @author Shofia Nabila Elfa Rahma_2110010113
 */
import java.awt.*;
public class PenampilGambarButton extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButton
     */
    public PenampilGambarButton() {
        initComponents();
        
        Dimension screenSize = 
        Toolkit.getDefaultToolkit().getScreenSize();
            Dimension frameSize = this.getSize();
            if (frameSize.height > screenSize.height) {
                frameSize.height = screenSize.height;
            }
            if (frameSize.width > screenSize.width) {
                frameSize.width = screenSize.width;
            }
            this.setLocation(
                    (screenSize.width - frameSize.width) / 2, 
                    (screenSize.height - frameSize.height) / 2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        bt_AppStore = new javax.swing.JButton();
        bt_YouTube = new javax.swing.JButton();
        bt_Google = new javax.swing.JButton();
        bt_Keluar = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        lbMl = new javax.swing.JLabel();
        lbCodm = new javax.swing.JLabel();
        lbPubg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonPanel.setBackground(new java.awt.Color(0, 0, 0));

        bt_AppStore.setText("APP STORE");
        bt_AppStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AppStoreActionPerformed(evt);
            }
        });
        buttonPanel.add(bt_AppStore);

        bt_YouTube.setText("YOUTUBE");
        bt_YouTube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_YouTubeActionPerformed(evt);
            }
        });
        buttonPanel.add(bt_YouTube);

        bt_Google.setText("GOOGLE");
        bt_Google.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_GoogleActionPerformed(evt);
            }
        });
        buttonPanel.add(bt_Google);

        bt_Keluar.setText("KELUAR");
        bt_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_KeluarActionPerformed(evt);
            }
        });
        buttonPanel.add(bt_Keluar);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        lbMl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kafka_2.jpg"))); // NOI18N
        imagePanel.add(lbMl, "2");

        lbCodm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kafka_1.jpg"))); // NOI18N
        imagePanel.add(lbCodm, "1");

        lbPubg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/kafka_3.jpg"))); // NOI18N
        imagePanel.add(lbPubg, "0");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AppStoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AppStoreActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "1");
    }//GEN-LAST:event_bt_AppStoreActionPerformed

    private void bt_YouTubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_YouTubeActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "0");
    }//GEN-LAST:event_bt_YouTubeActionPerformed

    private void bt_GoogleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_GoogleActionPerformed
        CardLayout cl = (CardLayout)(imagePanel.getLayout());
        cl.show(imagePanel, "2");
    }//GEN-LAST:event_bt_GoogleActionPerformed

    private void bt_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_KeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenampilGambarButton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_AppStore;
    private javax.swing.JButton bt_Google;
    private javax.swing.JButton bt_Keluar;
    private javax.swing.JButton bt_YouTube;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel lbCodm;
    private javax.swing.JLabel lbMl;
    private javax.swing.JLabel lbPubg;
    // End of variables declaration//GEN-END:variables
}
