/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AplikasiPenampilGambar;

/**
 *
 * @author Shofia Nabila Elfa Rahma_2110010113
 */
import java.awt.*;
public class PenampilGambarFullScreen extends javax.swing.JFrame {

    /**
     * Creates new form PilihGambarButtonFullScreen
     */
    public PenampilGambarFullScreen() {
        initComponents();
        Dimension screenSize = 
        Toolkit.getDefaultToolkit().getScreenSize();
            Dimension frameSize = this.getSize();
            if (frameSize.height > screenSize.height) {
                frameSize.height = screenSize.height;
            }
            if (frameSize.width > screenSize.width) {
                frameSize.width = screenSize.width;
            }
            this.setLocation(
                    (screenSize.width - frameSize.width) / 2, 
                    (screenSize.height - frameSize.height) / 2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        bt_DIscord = new javax.swing.JButton();
        bt_Spotify = new javax.swing.JButton();
        bt_Email = new javax.swing.JButton();
        bt_Keluar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblCodm = new javax.swing.JLabel();
        lblMl = new javax.swing.JLabel();
        lblPubg = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        bt_DIscord.setText("DISCORD");
        bt_DIscord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DIscordActionPerformed(evt);
            }
        });

        bt_Spotify.setText("SPOTIFY");
        bt_Spotify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SpotifyActionPerformed(evt);
            }
        });

        bt_Email.setText("EMAIL");
        bt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EmailActionPerformed(evt);
            }
        });

        bt_Keluar.setText("KELUAR");
        bt_Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_KeluarActionPerformed(evt);
            }
        });

        jPanel3.setLayout(new java.awt.CardLayout());

        lblCodm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/app_1.jpg"))); // NOI18N
        jPanel3.add(lblCodm, "1");

        lblMl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/app_2.jpg"))); // NOI18N
        jPanel3.add(lblMl, "2");

        lblPubg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPubg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/app_3.jpg"))); // NOI18N
        jPanel3.add(lblPubg, "0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Spotify)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_DIscord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Keluar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_DIscord)
                    .addComponent(bt_Spotify)
                    .addComponent(bt_Email)
                    .addComponent(bt_Keluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EmailActionPerformed
        CardLayout cl = (CardLayout)(jPanel3.getLayout());
        cl.show(jPanel3, "1");
    }//GEN-LAST:event_bt_EmailActionPerformed

    private void bt_SpotifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SpotifyActionPerformed
        CardLayout cl = (CardLayout)(jPanel3.getLayout());
        cl.show(jPanel3, "0");
    }//GEN-LAST:event_bt_SpotifyActionPerformed

    private void bt_DIscordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DIscordActionPerformed
        CardLayout cl = (CardLayout)(jPanel3.getLayout());
        cl.show(jPanel3, "2");
    }//GEN-LAST:event_bt_DIscordActionPerformed

    private void bt_KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_KeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenampilGambarFullScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PenampilGambarFullScreen fullFrame = new PenampilGambarFullScreen();
                
                GraphicsDevice device =
                        GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
                device.setFullScreenWindow(fullFrame);
                
                fullFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_DIscord;
    private javax.swing.JButton bt_Email;
    private javax.swing.JButton bt_Keluar;
    private javax.swing.JButton bt_Spotify;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCodm;
    private javax.swing.JLabel lblMl;
    private javax.swing.JLabel lblPubg;
    // End of variables declaration//GEN-END:variables
}
